pool: NewPool

variables:
- group: build-vars-tf

steps:
- task: DownloadSecureFile@1
  name: conjurCert
  displayName: 'Download CA certificate'
  inputs:
    secureFile: 'conjur-dev.pem'

- bash: |
    summon terraform apply
